const doneCountTask = document.querySelector(".done-count-task")
const doneClearAllBtn = document.querySelector(".done-clear-all-btn")
const doneList = document.querySelector("#done-list")
const viewDoneBtn = document.querySelector("#view-done")
const hideDoneBtn = document.querySelector("#hide-done")
const secondList = document.querySelector(".second-list")
const doneTasksFromLocalStorage = JSON.parse(localStorage.getItem("doneTask"))